layouts:
  [
    { # Settings Box
      type: "QGridLayout",
      name: "settingsBox",
      label: "Settings",
      widgets:
        [
          # File input
          { position: [0,0], type: "QLabel", label: "File input" },
          { position: [1,0], type: "QLineEdit", name: "editFileInput"},
          { position: [1,1], type: "QPushButton", name: "btnFileInput" },
          { position: [1,2], type: "QPushButton", name: "btnMeta" },
          # Central frequency
          { position: [2,0], type: "QLabel", label: "Central frequency [Hz]" },
          { position: [2,1], type: "QLineEdit", name: "freqCentral" },
          { position: [2,2], type: "QLabel", label: "Use data mean" },
          { position: [2,3], type: "QCheckBox", name: "checkCentral" },
          # Sampling frequency
          { position: [3,0], type: "QLabel", label: "Sampling frequency [Hz]" },
          { position: [3,1], type: "QLineEdit", name: "freqSampling" },
          # Tau min
          { position: [4,0], type: "QLabel", label: "Tau min [s]" },
          { position: [4,1], type: "QLineEdit", name: "tauMin" },
          { position: [4,2], type: "QLabel", label: "Set min tau" },
          { position: [4,3], type: "QCheckBox", name: "checkTauMin" },
          # Tau max
          { position: [5,0], type: "QLabel", label: "Tau max [s]" },
          { position: [5,1], type: "QLineEdit", name: "tauMax" },
          { position: [5,2], type: "QLabel", label: "Set max tau" },
          { position: [5,3], type: "QCheckBox", name: "checkTauMax" },
          # Tau N
          { position: [6,0], type: "QLabel", label: "Tau N" },
          { position: [6,1], type: "QLineEdit", name: "tauN" },
          # File output
          { position: [7,0], type: "QLabel", label: "File output" },
          { position: [8,0], type: "QLineEdit", name: "editFileOutput" },
          { position: [8,1], type: "QPushButton", name: "btnFileOutput" },
          { position: [8,2], type: "QPushButton", name: "btnSave" } 
        ]
    },
    { # Choosing deviation type
      type: "QGridLayout",
      name: "deviationBox",
      label: "Deviations",
      widgets:
        [
          { position: [0,0], type: "QLabel", label: "Allan" },
          { position: [0,1], type: "QCheckBox", name: "checkAllan" },
          { position: [0,2], type: "QLabel", label: "Allan overlapping" },
          { position: [0,3], type: "QCheckBox", name: "checkAllanOvlp" },
          { position: [0,4], type: "QLabel", label: "Hadamard" },
          { position: [0,5], type: "QCheckBox", name: "checkHadamard" },
        ]
    },
    { # Buttons Box
      type: "QHBoxLayout",
      name: "buttonsBox",
      label: "Buttons",
      widgets:
        [
          { type: "QPushButton", name: "btnAnalyse" }
        ]
    },
  ]

mainLayout:
  { # Main layout
    name: "mainLayout",
    type: "QVBoxLayout",
    contents:
      [
        { # Upper main box
          name: "upperBox", type: "QHBoxLayout", stretch: 6, contents:
          [
            { name: "upperLeftBox", type: QVBoxLayout, stretch: 1, contents:
              [
                { name: "settingsGroup", type: "QGroupBox", label: "Settings", contents: 
                  [
                  { name: "settingsBox", type: "layout", contents: [] }
                  ]
                },
                { name: "deviationGroup", type: "QGroupBox", label: "Deviation type", contents:
                  [
                    { name: "deviationBox", type: "layout", contents: [] }
                  ]
                },
                { name: "buttonsBox", type: "layout", contents: [] }
              ]
            },
            { name: "canvasDev", type: "widget", stretch: 2, contents: [] }
          ]
        },
        { # Lower main box
          name: "lowerBox", type: "QHBoxLayout", stretch: 5, contents: 
          [
            { name: "canvasFreq", type: "widget", stretch: 1, contents: []},
            { name: "canvasHist", type: "widget", stretch: 1, contents: []}
          ] 
        }
      ]
  }