QLineEdit:
  [
    { name: "freqCentral", label: "Central frequency [Hz]", default: "1e6" },
    { name: "freqSampling", label: "Sampling frequency [Hz]", default: "1e3" },
    { name: "tauMin", label: "Tau min [s]", default: "1" },
    { name: "tauMax", label: "Tau max [s]", default: "10" },
    { name: "tauN", label: "Tau N", default: "20" },
    { name: "editFileInput", label: "Input file" },
    { name: "editFileOutput", label: "Output file", default: "./data/deviation.csv" }
  ]
QPushButton:
  [
    { name: "btnAnalyse", label: "Analyse" },
    { name: "btnFileInput", label: "Choose file" },
    { name: "btnFileOutput", label: "Choose file" },
    { name: "btnSave", label: "Save" },
    { name: "btnMeta", label: "Load metadata" }
  ]
QCheckBox:
  [
    { name: "checkCentral", label: "Use data avg"},
    { name: "checkAllan", label: "Allan deviation" },
    { name: "checkAllanOvlp", label: "Allan overlapping deviation" },
    { name: "checkHadamard", label: "Hadamard deviation" },
    { name: "checkTauMin", label: "Set min tau" },
    { name: "checkTauMax", label: "Set max tau" }
  ]
PlotCanvas:
  [
    { name: "canvasDev", xlabel: "Tau [s]", ylabel: "Deviation", toolbar: True, settings: {yLog: 1, Grid: 1} },
    { name: "canvasHist", xlabel: "Frequency [Hz]", ylabel: "Counts", toolbar: False },
    { name: "canvasFreq", xlabel: "Time [s]", ylabel: "Fractional frequency", toolbar: False }
  ]